### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by BartoszBartmanski** [bacadra/atom-bib-finder#1]
I get the following error when I try to install this package

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.1
**Thrown From**: [bib-finder](https://github.com/bacadra/bib-finder) package 0.2.9

### Stack Trace

Uncaught Error: Cannot find module './src/BibTeX'
Require stack:
- /home/bartosz/.atom/packages/bib-finder/node_modules/@hygull/bibtex/index.js
- /home/bartosz/.atom/packages/bib-finder/lib/bib-finder-view.js
- /home/bartosz/.atom/packages/bib-finder/lib/bib-finder.js
- /usr/share/atom/resources/app.asar/static/index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module './src/BibTeX'
Require stack:
- /home/bartosz/.atom/packages/bib-finder/node_modules/@hygull/bibtex/index.js
- /home/bartosz/.atom/packages/bib-finder/lib/bib-finder-view.js
- /home/bartosz/.atom/packages/bib-finder/lib/bib-finder.js
- /usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/bib-finder/node_modules/@hygull/bibtex/index.js:1:171)
    at /packages/bib-finder/node_modules/@hygull/bibtex/index.js:4:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/bib-finder/lib/bib-finder-view.js:8:16)
    at /packages/bib-finder/lib/bib-finder-view.js:10:36)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/bib-finder/lib/bib-finder.js:3:41)
    at /packages/bib-finder/lib/bib-finder.js:51:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:696928)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3578827)
    at Package.activateConfig (/usr/share/atom/resources/app/static/<embedded>:11:3568115)
    at PackageManager.packageHasSettings (/usr/share/atom/resources/app/static/<embedded>:11:910108)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/static/<embedded>:14:2639258)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/static/<embedded>:14:2629526)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/static/<embedded>:14:2629349)
    at /usr/share/atom/resources/app/static/<embedded>:14:2637491
    at /usr/share/atom/resources/app/static/<embedded>:14:2639509
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191492)
    at PackageManager.emitPackageEvent (/usr/share/atom/resources/app/static/<embedded>:11:919565)
    at /usr/share/atom/resources/app/static/<embedded>:11:916697
    at r (/usr/share/atom/resources/app/static/<embedded>:11:911227)
    at s (/usr/share/atom/resources/app/static/<embedded>:14:1134638)
    at /usr/share/atom/resources/app/static/<embedded>:14:1134792
    at Socket.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:1133394)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
     -2:31.3.0 core:cancel (input.hidden-input)
     -2:29.5.0 intentions:highlight (input.hidden-input)
     -2:29.3.0 command-palette:toggle (input.hidden-input)
     -2:26.4.0 editor:consolidate-selections (input.hidden-input)
     -2:26.4.0 core:cancel (input.hidden-input)
     -2:25.9.0 intentions:highlight (input.hidden-input)
  4x -2:25.6.0 latex-tree:toggle-tree-view (input.hidden-input)
     -2:21.4.0 intentions:highlight (input.hidden-input)
     -2:21.3.0 core:save (input.hidden-input)
     -2:19.4.0 intentions:highlight (input.hidden-input)
     -2:19.3.0 pane:show-next-item (input.hidden-input)
     -2:18.7.0 intentions:highlight (input.hidden-input)
     -2:18.2.0 pane:show-previous-item (input.hidden-input)
     -2:17.3.0 pane:show-next-item (input.hidden-input)
  3x -1:03.2.0 intentions:highlight (input.hidden-input)
     -1:02.4.0 pane:show-next-item (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
autocomplete-bash-builtins 0.3.5 
autocomplete-clang 0.13.1 
autocomplete-cmake 0.3.1 
autocomplete-latex 1.0.0 
autocomplete-latex-references 0.3.2 
autocomplete-paths 2.12.15 
autocomplete-python 1.16.0 
bib-finder 0.2.9 
busy-signal 2.0.1 
dbg 1.6.3 
dbg-gdb 1.7.8 
intentions 1.1.5 
language-cmake 1.2.0 
language-fortran 2.1.12 
language-latex 1.2.0 
latex-tree 0.5.0 
linter 3.2.3 
linter-gcc 0.9.0 
linter-python 3.1.2 
linter-ui-default 2.4.0 
materia-syntax 0.0.0 
minimap 4.37.1 
output-panel 0.3.4 
pdf-view-plus 1.11.0 
python-indent 1.2.6 
python-tools 0.6.9 
scroll-through-time 0.3.1 
split-diff 1.6.1 
Sublime-Style-Column-Selection 1.7.5 
symbols-tree-view 0.14.0 
teletype 0.13.4 
```

**Comment by asiloisad** [comment]
hi, i just noticed your problem. can you check whether the problem still occurs? 
I checked the installation of package with a clean .atom version and I don't see any problems.
best regards

**Comment by BartoszBartmanski** [comment]
Hi! Thanks for looking into it. I tried installing bib-finder again on the newest version of Atom (1.57.0) and got the same error

**Comment by asiloisad** [comment]
today i changed the bibtex parser library. it resolve your problem probably.
